repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12
        additional_dependencies: [click==8.1.7]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.2.5
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.2.5"]
        files: "frontend/src/.*\.(ts|tsx|js|jsx|css|json)"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.3.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@9.33.0
          - '@eslint/js@9.33.0'
          - typescript@5.8.3
          - eslint-plugin-react-hooks@5.2.0
          - eslint-plugin-react-refresh@0.4.20
        files: frontend/src/.*\.(ts|tsx|js|jsx)
