version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: nutriai-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: nutriai
      POSTGRES_USER: nutriai_user
      POSTGRES_PASSWORD: nutriai123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nutriai-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: nutriai-redis
    ports:
      - "6379:6379"
    networks:
      - nutriai-network
    restart: unless-stopped

  server:
    build: ./server
    container_name: nutriai-server
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://nutriai_user:nutriai123@postgres:5432/nutriai
      - REDIS_URL=redis://redis:6379
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - USDA_API_KEY=${USDA_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
      - redis
    ports:
      - "3001:3001"
    networks:
      - nutriai-network
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped

  client:
    build: ./client
    container_name: nutriai-client
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_TELEGRAM_BOT_NAME=${TELEGRAM_BOT_NAME}
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - nutriai-network
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped

networks:
  nutriai-network:
    driver: bridge

volumes:
  postgres_data:
